language: go

env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=84c4895fcde8b9ad85469b325f08337b5a7953a5b0508b0cf0fe7a38acf3271b

stages:
  - test
  - deploy

go:
  - 1.13.x

sudo: required
dist: trusty

before_install:
  - go get -u golang.org/x/lint/golint
  - make deps

jobs:
  include:
    - stage: test
      name: "Run tests"
      script: make test

    - stage: test
      name: "Generate coverage"
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: make test-coverage
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: deploy
      name: "Deployment"
      if: tag IS present
      before_script: make deps
      script: make release
      deploy:
        provider: releases
        overwrite: true
        file:
          - release/edm-linux-amd64
          - release/edm-linux-arm
          - release/edm-linux-386
          - release/edm-mac-amd64
          - release/edm-windows-amd64.exe
          - release/edm-windows-386.exe
        skip_cleanup: true
        on:
          repo: svenfinke/edm
          tags: true